{
  "swagger": "2.0",
  "info": {
    "description": "Nuestros Smart Contracts son programas informáticos que ejecutan, controlan o supervisan automáticamente las transacciones y acciones legalmente relevantes definidas por un contrato o un acuerdo comercial.",
    "version": "v1",
    "title": "Seif para desarrolladores API",
    "termsOfService": "https://seif.io/",
    "contact": { "email": "juang@seif.com" },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "x-logo": {
      "url": "https://seif.io/wp-content/uploads/2018/05/logo-seif-dark-1.png",
      "backgroundColor": "#FFFFFF",
      "altText": "Seif logo"
    }
  },

  "host": "seif.io",
  "basePath": "/v2",
  "tags": [
    {
      "name": "Enrrollment",
      "description": "Seif Ocr, este sistema se dedica a la indetificacion de usuarios mediante mecanismo de KYC",
      "externalDocs": {
        "description": "Si deseas saber haz click aqui",
        "url": "http://swagger.io"
      }
    },
    {
      "name": "Ifrit",
      "description": "Apolo UI open source",
      "externalDocs": {
        "description": "Si deseas saber haz click aqui",
        "url": "http://swagger.io"
      }
    },

    {
      "name": "Fenrir",
      "description": "Conexion de api para clientes y registro en padron de provedores",
      "externalDocs": {
        "description": "Si deseas saber haz click aqui",
        "url": "https://seif.io"
      }
    },
    {
      "name": "Chaincode session",
      "description": "Estamos construyendo un ecosistema blockchain con nuestros clientes y sus clientes, y sus proveedores, para poder ofrecerle una blockchain verdaderamente descentralizada.",
      "externalDocs": {
        "description": "Si deseas saber haz click aqui",
        "url": "https://seif.io/#ecosystem"
      }
    },
    {
      "name": "Chaincode Identidad",
      "description": "Estamos construyendo un ecosistema blockchain con nuestros clientes y sus clientes, y sus proveedores, para poder ofrecerle una blockchain verdaderamente descentralizada.",
      "externalDocs": {
        "description": "Si deseas saber haz click aqui",
        "url": "https://seif.io/#ecosystem"
      }
    },
    {
      "name": "Chaincode Contrato",
      "description": "Estamos construyendo un ecosistema blockchain con nuestros clientes y sus clientes, y sus proveedores, para poder ofrecerle una blockchain verdaderamente descentralizada.",
      "externalDocs": {
        "description": "Si deseas saber haz click aqui",
        "url": "https://seif.io/#ecosystem"
      }
    },
    {
      "name": "Chaincode Transaccion",
      "description": "Estamos construyendo un ecosistema blockchain con nuestros clientes y sus clientes, y sus proveedores, para poder ofrecerle una blockchain verdaderamente descentralizada.",
      "externalDocs": {
        "description": "Si deseas saber haz click aqui",
        "url": "https://seif.io/#ecosystem"
      }
    },
    {
      "name": "Chaincode Business Rule",
      "description": "Estamos construyendo un ecosistema blockchain con nuestros clientes y sus clientes, y sus proveedores, para poder ofrecerle una blockchain verdaderamente descentralizada.",
      "externalDocs": {
        "description": "Si deseas saber haz click aqui",
        "url": "https://seif.io/#ecosystem"
      }
    }
  ],

  "servers": [
    {
      "url": "https://enrrollment.seif.io",
      "description": "Servidor de enrrollment"
    }
  ],

  "schemes": ["https"],

  "paths": {
    "/enrrollment/api/": {
      "get": {
        "summary": "Ir a usuario",
        "tags": ["Enrrollment"],
        "parameters": [
          {
            "name": "userId",
            "required": true,
            "type": "string",
            "in": "query",
            "description": "Id de usuario"
          }
        ],
        "responses": {
          "200": {
            "description": "Usuario encontrado",
            "headers": {}
          },
          "400": {
            "description": "Usuario  desconocido",
            "headers": {}
          }
        }
      }
    },
    "/enrrollment/api/byCurp": {
      "get": {
        "summary": "Ir a usuario por CURP",
        "description": "En este servicio se púeden realizar busquedas mediante el curp del usuario (Exclusivo para mexicanos) si deseas saber mas <a href='https://www.gob.mx/segob/acciones-y-programas/clave-unica-de-registro-de-poblacion-curp'>haz click aqui</a>",
        "tags": ["Enrrollment"],
        "parameters": [
          {
            "name": "curp",
            "required": true,
            "type": "string",
            "in": "query",
            "description": "Curp de usuario"
          }
        ],
        "responses": {
          "200": {
            "description": "Usuario encontrado",
            "headers": {}
          },
          "400": {
            "description": "Usuario  desconocido",
            "headers": {}
          }
        }
      }
    },
    "/enrrollment/api/byContact": {
      "get": {
        "summary": "Ir a usuario por contacto",
        "description": "En este servicio se púeden realizar busquedas mediante el contacto o telefono",
        "tags": ["Enrrollment"],

        "parameters": [
          {
            "name": "contact",
            "required": true,
            "type": "string",
            "in": "query",
            "description": "Contacto de usuario"
          }
        ],
        "responses": {
          "200": {
            "description": "Usuario encontrado",
            "headers": {}
          },
          "400": {
            "description": "Usuario  desconocido",
            "headers": {}
          }
        }
      }
    },
    "/enrrollment/api/contactInformation": {
      "post": {
        "summary": "Añadir informacion de usuario",
        "description": "En este servicio puedes añadir la informacion del usuario",
        "tags": ["Enrrollment"],
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "title": "contactInformation",
              "example": {
                "user": {
                  "email": "example@example.com",
                  "phone": "+55555555",
                  "id": "XXXXXXXXXXX",
                  "phone_verified": true,
                  "mail_verified": false
                }
              },
              "type": "object",
              "properties": {
                "email": {
                  "type": "string"
                },
                "phone": {
                  "type": "string"
                },
                "id": {
                  "type": "string"
                },
                "phone_verified": {
                  "type": "boolean"
                },
                "mail_verified": {
                  "type": "boolean"
                }
              },
              "required": [
                "email",
                "phone",
                "id",
                "phone_verified",
                "mail_verified"
              ]
            }
          }
        ],

        "responses": {
          "200": {
            "description": "Usuario encontrado",
            "headers": {}
          },
          "400": {
            "description": "Usuario  desconocido",
            "headers": {}
          }
        }
      }
    },
    "/enrrollment/api/confirmationCode": {
      "post": {
        "summary": "Enviar codigo de confirmacion",
        "description": "Este servicio puede enviar un codigo de confirmacion via sms",
        "tags": ["Enrrollment"],
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "title": "contactInformation",
              "example": {
                "confirmation": "ID_USER"
              },
              "type": "object",
              "properties": {
                "confirmation": {
                  "type": "string"
                }
              },
              "required": ["confirmation"]
            }
          }
        ],

        "responses": {
          "200": {
            "description": "Usuario encontrado",
            "headers": {}
          },
          "400": {
            "description": "Usuario  desconocido",
            "headers": {}
          }
        }
      },
      "put": {
        "summary": "Renvia codigo de confirmacion",
        "description": "Este servicio puede enviar un codigo de confirmacion via sms",
        "tags": ["Enrrollment"],
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "title": "contactInformation",
              "example": {
                "code": "ID_USER"
              },
              "type": "object",
              "properties": {
                "code": {
                  "type": "string"
                }
              },
              "required": ["code"]
            }
          }
        ],

        "responses": {
          "200": {
            "description": "Usuario encontrado",
            "headers": {}
          },
          "400": {
            "description": "Usuario  desconocido",
            "headers": {}
          }
        }
      }
    },
    "/enrrollment/api/basicInformation": {
      "put": {
        "summary": "Editar informacion",
        "description": "En este servicio puedes añadir la informacion del usuario",
        "tags": ["Enrrollment"],
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "title": "basicInformation",
              "example": {
                "user": {
                  "email": "example@example.com",
                  "phone": "+55555555",
                  "id": "XXXXXXXXXXX"
                }
              },
              "type": "object",
              "properties": {
                "email": {
                  "type": "string"
                },
                "phone": {
                  "type": "string"
                },
                "id": {
                  "type": "string"
                }
              },
              "required": ["id"]
            }
          }
        ],

        "responses": {
          "200": {
            "description": "Usuario encontrado",
            "headers": {}
          },
          "400": {
            "description": "Usuario  desconocido",
            "headers": {}
          }
        }
      }
    },
    "/enrrollment/api/validateIne": {
      "post": {
        "summary": "Validar informacion de  Ine (KYC)",
        "description": "Este mecanismo usa un sistema OCR por lo cual es vital del uso de un FileDataForm",
        "tags": ["Enrrollment"],
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "title": "basicInformation",
              "example": {
                "card_front": "FileData()",
                "card_back": "FileData()",
                "curp": "XXXXXXXXXXX"
              },
              "type": "object",
              "properties": {
                "card_front": {
                  "type": "FileForm"
                },
                "card_back": {
                  "type": "FileForm"
                },
                "curp": {
                  "type": "string"
                }
              },
              "required": ["curp", "card_front", "card_back"]
            }
          }
        ],

        "responses": {
          "200": {
            "description": "Usuario encontrado",
            "headers": {}
          },
          "400": {
            "description": "Usuario  desconocido",
            "headers": {}
          }
        }
      }
    },
    "/enrrollment/api/validatePicture": {
      "post": {
        "summary": "Validar imagen de usuario (KYC)",
        "description": "En este servicio se puede añadir el rostro de un usuario mediante IA",
        "tags": ["Enrrollment"],
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "title": "basicInformation",
              "example": {
                "picture": "FileData()"
              },
              "type": "object",
              "properties": {
                "picture": {
                  "type": "FileForm"
                }
              },
              "required": ["picture"]
            }
          }
        ],

        "responses": {
          "200": {
            "description": "Usuario encontrado",
            "headers": {}
          },
          "400": {
            "description": "Usuario  desconocido",
            "headers": {}
          }
        }
      }
    },
    "/enrrollment/api/validateAddress": {
      "post": {
        "summary": "Validar domicilio (KYC)",
        "description": "En este servicio se puede validar el domicilio del usuario",
        "tags": ["Enrrollment"],
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "title": "validateAddress",
              "example": {
                "address_file": "FileData()",
                "country": "Ca",
                "city": "Mountain View,",
                "street": "1600 Amphitheatre Pkwy",
                "cp": "94043"
              },
              "type": "object",
              "properties": {
                "address_file": {
                  "type": "FileForm"
                },
                "country": {
                  "type": "String"
                },
                "city": {
                  "type": "String"
                },
                "street": {
                  "type": "String"
                },
                "cp": {
                  "type": "String"
                }
              },
              "required": [
                "address_file",
                "country",
                "city",
                "cp",
                "street",
                "cp",
                "cp"
              ]
            }
          }
        ],

        "responses": {
          "200": {
            "description": "Usuario encontrado",
            "headers": {}
          },
          "400": {
            "description": "Usuario  desconocido",
            "headers": {}
          }
        }
      }
    },
    "/api/search/:id": {
      "get": {
        "summary": "Busqueda de contrato, usuario o transacción",
        "tags": ["Ifrit"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "id",
            "required": true,
            "type": "string",
            "in": "path",
            "description": "Introduce el número de tu contrato, usuario o transacción"
          }
        ],
        "responses": {
          "200": {
            "description": "Repuesta de busqueda correcta",
            "headers": {}
          },
          "400": {
            "description": "Respuesta de busqueda incorrecta",
            "headers": {}
          }
        }
      }
    },
    "/channels/mychannel/chaincodes/identity": {
      "get": {
        "summary": "Consulta Identidad",
        "tags": ["Chaincode Identidad"],
        "operationId": "ConsultaIdentidad",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "args",
            "in": "query",
            "required": true,
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          },
          {
            "name": "fcn",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "post": {
        "summary": "Registra Identidad",
        "tags": ["Chaincode Identidad"],
        "operationId": "RegistraIdentidad",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/RegistraIdentidadRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/channels/mychannel/chaincodes/identidad": {
      "get": {
        "summary": "Consulta por Asset",
        "tags": ["Chaincode Identidad"],
        "operationId": "ConsultaporAsset",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "args",
            "in": "query",
            "required": true,
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          },
          {
            "name": "fcn",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/channels/mychannel/chaincodes/participant": {
      "post": {
        "summary": "Registra Participante",
        "tags": ["Chaincode Contrato"],
        "operationId": "RegistraParticipante",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/RegistraParticipanteRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "get": {
        "summary": "Consulta Participante",
        "tags": ["Chaincode Contrato"],
        "operationId": "ConsultaParticipante",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "args",
            "in": "query",
            "required": true,
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          },
          {
            "name": "fcn",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/channels/mychannel/chaincodes/agreement": {
      "post": {
        "summary": "Registra Contrato",
        "tags": ["Chaincode Contrato"],
        "operationId": "RegistraContrato",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/RegistraContratoRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "get": {
        "summary": "Consulta Contrato",
        "tags": ["Chaincode Contrato"],
        "operationId": "ConsultaContrato",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "args",
            "in": "query",
            "required": true,
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          },
          {
            "name": "fcn",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/channels/mychannel/chaincodes/transaction": {
      "post": {
        "summary": "Registra Transaccion",
        "tags": ["Chaincode Transaccion"],
        "operationId": "RegistraTransaccion",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/RegistraTransaccionRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "get": {
        "summary": "Consulta Transaccion",
        "tags": ["Chaincode Transaccion"],
        "operationId": "ConsultaTransaccion",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "args",
            "in": "query",
            "required": true,
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          },
          {
            "name": "fcn",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/channels/mychannel/chaincodes/businessrule": {
      "post": {
        "summary": "Registra Business Rule",
        "tags": ["Chaincode Business Rule"],
        "operationId": "RegistraBusinessRule",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/RegistraBusinessRuleRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "get": {
        "summary": "Consulta Business Rule",
        "tags": ["Chaincode Business Rule"],
        "operationId": "ConsultaBusinessRule",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "args",
            "in": "query",
            "required": true,
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          },
          {
            "name": "fcn",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/": {
      "get": {
        "summary": "Status API",
        "tags": ["Chaincode session"],
        "operationId": "StatusAPI",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/users": {
      "post": {
        "summary": "Registrar Usuario",
        "tags": ["Chaincode session"],
        "operationId": "RegistrarUsuario",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/RegistrarUsuarioRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/users/login": {
      "post": {
        "summary": "Login Usuario",
        "tags": ["Chaincode session"],
        "operationId": "LoginUsuario",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/LoginUsuarioRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },

    "/authenticate": {
      "get": {
        "summary": "AuthLV",
        "tags": ["Fenrir"],
        "operationId": "AuthLV",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "X-TenantID",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/hook/reference": {
      "post": {
        "summary": "Crear referencia",
        "tags": ["Fenrir"],
        "operationId": "Crearreferencia",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "api_key",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Client_Secret",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/CrearreferenciaRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/oauth/generate": {
      "post": {
        "summary": "OAUTH SEIF",
        "tags": ["Fenrir"],
        "operationId": "OAUTHSEIF",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/lv/certificate/generate": {
      "post": {
        "summary": "Generate",
        "tags": ["Fenrir"],
        "operationId": "Generate",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/GenerateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/lv/credit-info/{code}/{token}": {
      "get": {
        "summary": "Info Credit",
        "tags": ["Fenrir"],
        "operationId": "InfoCredit",
        "deprecated": false,
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "code",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    }
  },
  "definitions": {
    "CrearreferenciaRequest": {
      "title": "CrearreferenciaRequest",
      "example": {
        "idValidacion": 2456346,
        "idReferencia": 3434545,
        "nombresCliente": "Pablo hernandez",
        "nombresReferencia": "Juan Vazquez",
        "telefonoReferencia": "55555555",
        "tipoReferencia": "FAMILIAR",
        "parentesco": "PAPA",
        "estadoVerificacion": "APROBADO"
      },
      "type": "object",
      "properties": {
        "idValidacion": {
          "type": "integer",
          "format": "int32"
        },
        "idReferencia": {
          "type": "integer",
          "format": "int32"
        },
        "nombresCliente": {
          "type": "string"
        },
        "nombresReferencia": {
          "type": "string"
        },
        "telefonoReferencia": {
          "type": "string"
        },
        "tipoReferencia": {
          "type": "string"
        },
        "parentesco": {
          "type": "string"
        },
        "estadoVerificacion": {
          "type": "string"
        }
      },
      "required": [
        "idValidacion",
        "idReferencia",
        "nombresCliente",
        "nombresReferencia",
        "telefonoReferencia",
        "tipoReferencia",
        "parentesco",
        "estadoVerificacion"
      ]
    },
    "ActualizarbotRequest": {
      "title": "ActualizarbotRequest",
      "example": {
        "idReferencia": 3434549,
        "telefonoReferencia": "+525533654162",
        "estadoVerificacion": "RECHAZADO"
      },
      "type": "object",
      "properties": {
        "idReferencia": {
          "type": "integer",
          "format": "int32"
        },
        "telefonoReferencia": {
          "type": "string"
        },
        "estadoVerificacion": {
          "type": "string"
        }
      },
      "required": ["idReferencia", "telefonoReferencia", "estadoVerificacion"]
    },
    "GenerateRequest": {
      "title": "GenerateRequest",
      "example": {
        "credito": "202324",
        "hash": "d5385552c92f03c0d17839f0620ab0427e0c9534"
      },
      "type": "object",
      "properties": {
        "credito": {
          "type": "string"
        },
        "hash": {
          "type": "string"
        }
      },
      "required": ["credito", "hash"]
    },
    "GeneratesyncRequest": {
      "title": "GeneratesyncRequest",
      "example": {
        "credito": "202324",
        "hash": "d5385552c92f03c0d17839f0620ab0427e0c9534"
      },
      "type": "object",
      "properties": {
        "credito": {
          "type": "string"
        },
        "hash": {
          "type": "string"
        }
      },
      "required": ["credito", "hash"]
    },
    "RegistraIdentidadRequest": {
      "title": "RegistraIdentidadRequest",
      "example": {
        "fcn": "createIdentity",
        "peers": [
          "peer0.org1.midominio.com",
          "peer0.org2.midominio.com",
          "peer0.org3.midominio.com"
        ],
        "chaincodeName": "identity",
        "channelName": "mychannel",
        "args": [
          "CODE01",
          "AUDI111",
          "xxx",
          "xxx",
          "xx",
          "xx",
          "xx",
          "xx",
          "xx",
          "xx",
          "xx",
          "xx",
          "xx",
          "xx",
          "xx",
          "xx",
          "xx",
          "xx",
          "xx",
          "null",
          "null",
          "null"
        ]
      },
      "type": "object",
      "properties": {
        "fcn": {
          "type": "string"
        },
        "peers": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "chaincodeName": {
          "type": "string"
        },
        "channelName": {
          "type": "string"
        },
        "args": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["fcn", "peers", "chaincodeName", "channelName", "args"]
    },
    "RegistraParticipanteRequest": {
      "title": "RegistraParticipanteRequest",
      "example": {
        "fcn": "createParticipant",
        "peers": [
          "peer0.org1.midominio.com",
          "peer0.org2.midominio.com",
          "peer0.org3.midominio.com"
        ],
        "chaincodeName": "participant",
        "channelName": "mychannel",
        "args": ["88889", "AUDI111", "xxx", "xxx", "xx", "xx", "xx", "xx"]
      },
      "type": "object",
      "properties": {
        "fcn": {
          "type": "string"
        },
        "peers": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "chaincodeName": {
          "type": "string"
        },
        "channelName": {
          "type": "string"
        },
        "args": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["fcn", "peers", "chaincodeName", "channelName", "args"]
    },
    "RegistraContratoRequest": {
      "title": "RegistraContratoRequest",
      "example": {
        "fcn": "createAgreement",
        "peers": [
          "peer0.org1.midominio.com",
          "peer0.org2.midominio.com",
          "peer0.org3.midominio.com"
        ],
        "chaincodeName": "agreement",
        "channelName": "mychannel",
        "args": [
          "dummy_test89999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999",
          "88889",
          "dummy_test3_xname3333",
          "dummy_test3_xname4444",
          "dummy_test3_xname5555",
          "dummy_test3_xname666",
          "dummy_test3_xname777",
          "dummy_test3_xname88888",
          "dato1|dato2|dato3|dato4",
          "aaaa",
          "qqqqq"
        ]
      },
      "type": "object",
      "properties": {
        "fcn": {
          "type": "string"
        },
        "peers": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "chaincodeName": {
          "type": "string"
        },
        "channelName": {
          "type": "string"
        },
        "args": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["fcn", "peers", "chaincodeName", "channelName", "args"]
    },
    "RegistraTransaccionRequest": {
      "title": "RegistraTransaccionRequest",
      "example": {
        "fcn": "createTransaction",
        "peers": [
          "peer0.org1.midominio.com",
          "peer0.org2.midominio.com",
          "peer0.org3.midominio.com"
        ],
        "chaincodeName": "transaction",
        "channelName": "mychannel",
        "args": ["8888", "AUDI111", "xxx", "xxx", "xx", "xx", "xx", "xx"]
      },
      "type": "object",
      "properties": {
        "fcn": {
          "type": "string"
        },
        "peers": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "chaincodeName": {
          "type": "string"
        },
        "channelName": {
          "type": "string"
        },
        "args": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["fcn", "peers", "chaincodeName", "channelName", "args"]
    },
    "RegistraBusinessRuleRequest": {
      "title": "RegistraBusinessRuleRequest",
      "example": {
        "fcn": "createBusinessrule",
        "peers": [
          "peer0.org1.midominio.com",
          "peer0.org2.midominio.com",
          "peer0.org3.midominio.com"
        ],
        "chaincodeName": "businessrule",
        "channelName": "mychannel",
        "args": [
          "CCCCCC",
          "AUDI111",
          "xxx",
          "xxx",
          "xx",
          "xx",
          "xx",
          "xx",
          "x111111x",
          "xx1111"
        ]
      },
      "type": "object",
      "properties": {
        "fcn": {
          "type": "string"
        },
        "peers": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "chaincodeName": {
          "type": "string"
        },
        "channelName": {
          "type": "string"
        },
        "args": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["fcn", "peers", "chaincodeName", "channelName", "args"]
    },
    "RegistrarUsuarioRequest": {
      "title": "RegistrarUsuarioRequest",
      "example": {
        "username": "jorge2",
        "orgName": "Org1"
      },
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "orgName": {
          "type": "string"
        }
      },
      "required": ["username", "orgName"]
    },
    "LoginUsuarioRequest": {
      "title": "LoginUsuarioRequest",
      "example": {
        "username": "jorge1",
        "orgName": "Org1"
      },
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "orgName": {
          "type": "string"
        }
      },
      "required": ["username", "orgName"]
    }
  }
}
